package io.github.splotycode.spellchecker.english;

public enum Tense {

    SIMPLE_PRESENT,
    SIMPLE_PAST,
    SIMPLE_FUTURE,
    PRESENT_CONTINUOUS,
    PAST_CONTINUOUS,
    FUTURE_CONTINUOUS,
    PRESENT_PERFECT,
    PAST_PERFECT,
    FUTURE_PERFECT,
    PRESENT_PERFECT_CONTINOUS,
    PAST_PERFECT_CONTINOUS,
    FUTURE_PERFECT_CONTINOUS,;

}
